# Generated by Django 4.0.3 on 2022-03-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_themes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Themes',
            new_name='Theme',
        ),
    ]
