# Generated by Django 4.0.3 on 2022-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_scope_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=None, verbose_name='Основной'),
        ),
    ]
