# Generated by Django 4.0.3 on 2022-03-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='theme',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
    ]
