# Generated by Django 4.0.3 on 2022-03-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
