# Generated by Django 4.0.3 on 2022-03-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-name'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
