# Generated by Django 4.0.3 on 2022-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_theme_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
